name: api-helm
on:
  push:
    branches:
      - main
      - develop

  workflow_dispatch:
     
jobs:
  cluster-deploy:
    name: Deploy to cluster 
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Configuration for develop environment
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          echo "DEPLOYMENT=${{ secrets.DEPLOYMENT_DEV }}" >> $GITHUB_ENV
          echo $GITHUB_ENV
        # Setting env for staging if pushed to main branch
      - name: Configuration for staging
        if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch'}}
        run: |
          echo "DEPLOYMENT=${{ secrets.DEPLPYMENT_STG }}" >> $GITHUB_ENV
          echo $GITHUB_ENV
        # Setting env for production if triggered by workflow dispatch
      - name: Configuration for production
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
        run: |
          echo "DEPLOYMENT=${{ secrets.DEPLOYMENT_PROD }}" >> $GITHUB_ENV
          echo $GITHUB_ENV
